port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - 119.29.29.29
    - 180.76.76.76
  fallback:
    - https://162.159.36.1/dns-query
    - https://162.159.46.1/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://139.224.112.177/dns-query
    - https://162.14.13.12/dns-query
tun:
  enable: true
  stack: system
  dns-listen: 198.18.0.1:53
  device-url: "dev://utun"
